project_id = "nxbjgqdehvxszqjoxumx"

[functions.cutii-chat]
verify_jwt = true

[functions.submit-community-application]
verify_jwt = false

[functions.submit-kvkk-request]
verify_jwt = false

[functions.admin-stats]
verify_jwt = true
